//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizWebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using System.Net.Http;
    using System.Net;
    
    public partial class DBModel : DbContext
    {
        public DBModel()
            : base("name=DBModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Participant> Participants { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<ParticipantDetail> ParticipantDetails { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }

        public virtual int prcGetAllUsersGradeBook()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prcGetAllUsersGradeBook");
          //  return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prcGetAllUsersGradeBook");
        }
    }
}
